name: CI

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11']

    steps:
      - uses: actions/checkout@v2
      - uses: coursier/cache-action@v5

      - name: Set up JDK ${{ matrix.java }}
        uses: olafurpg/setup-scala@v12
        with:
          java-version: ${{ matrix.java }}

      - name: Run tests
        run: sbt clean test